# Dependabot will run on day 9 of each month at 01:07 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: 'npm'
    schedule:
      interval: 'cron'
      timezone: 'Europe/Berlin'
      cronjob: '7 1 9 * *'
    cooldown:
      default-days: 7
    open-pull-requests-limit: 15
    assignees:
      - 'FernetMenta'
    versioning-strategy: 'increase'
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'
    directories:
      - '/'
      - '/src-admin'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'cron'
      timezone: 'Europe/Berlin'
      cronjob: '7 1 9 * *'
    cooldown:
      default-days: 7
    open-pull-requests-limit: 15
    assignees:
      - 'FernetMenta'
