// SPDX-License-Identifier: Apache-2.0
// Copyright Pionix GmbH and Contributors to EVerest

syntax = "proto3";

option go_package = "github.com/enbility/eebus-grpc/rpc_services/usecases/eg/lpp";

package eg_lpp;

import "common_types/types.proto";

message ProductionLimitRequest {
    string instance_id = 1;
    string remote_ski = 2;
    common_types.EntityAddress remote_entity_address = 3;
}

message ProductionLimitResponse {
    common_types.LoadLimit limit = 1;
}

message WriteProductionLimitRequest {
    string instance_id = 1;
    string remote_ski = 2;
    common_types.EntityAddress remote_entity_address = 3;
    common_types.LoadLimit limit = 4;
}

message WriteProductionLimitResponse {
    optional uint64 error_number = 1;
    optional string description = 2;
    uint64 msg_counter = 3;
}

message FailsafeProductionActivePowerLimitRequest {
    string instance_id = 1;
    string remote_ski = 2;
    common_types.EntityAddress remote_entity_address = 3;
}

message FailsafeProductionActivePowerLimitResponse {
    double limit = 1;
}

message WriteFailsafeProductionActivePowerLimitRequest {
    string instance_id = 1;
    string remote_ski = 2;
    common_types.EntityAddress remote_entity_address = 3;
    double limit = 4;
}

message WriteFailsafeProductionActivePowerLimitResponse {
    uint64 msg_counter = 1;
}

message FailsafeDurationMinimumRequest {
    string instance_id = 1;
    string remote_ski = 2;
    common_types.EntityAddress remote_entity_address = 3;
}

message FailsafeDurationMinimumResponse {
    uint64 duration_nanoseconds = 1;
}

message WriteFailsafeDurationMinimumRequest {
    string instance_id = 1;
    string remote_ski = 2;
    common_types.EntityAddress remote_entity_address = 3;
    uint64 duration_nanoseconds = 4;
}

message WriteFailsafeDurationMinimumResponse {
    uint64 msg_counter = 1;
}

message StartHeartbeatRequest {
    string instance_id = 1;
}

message StartHeartbeatResponse {
}

message StopHeartbeatRequest {
    string instance_id = 1;
}

message StopHeartbeatResponse {
}

message IsHeartbeatWithinDurationRequest {
    string instance_id = 1;
    string remote_ski = 2;
    common_types.EntityAddress remote_entity_address = 3;
}

message IsHeartbeatWithinDurationResponse {
    bool within_duration = 1;
}

message ProductionNominalMaxRequest {
    string instance_id = 1;
    string remote_ski = 2;
    common_types.EntityAddress remote_entity_address = 3;
}

message ProductionNominalMaxResponse {
    double production_nominal_max = 1;
}
