// SPDX-License-Identifier: Apache-2.0
// Copyright Pionix GmbH and Contributors to EVerest

syntax = "proto3";

option go_package = "github.com/enbility/eebus-grpc/rpc_services/usecases/eg/lpp";

package eg_lpp;

import "usecases/eg/lpp/messages.proto";

service EnergyGuardLPPControl {
    rpc ProductionLimit (ProductionLimitRequest) returns (ProductionLimitResponse) {}
    rpc WriteProductionLimit (WriteProductionLimitRequest) returns (WriteProductionLimitResponse) {}
    rpc FailsafeProductionActivePowerLimit (FailsafeProductionActivePowerLimitRequest) returns (FailsafeProductionActivePowerLimitResponse) {}
    rpc WriteFailsafeProductionActivePowerLimit (WriteFailsafeProductionActivePowerLimitRequest) returns (WriteFailsafeProductionActivePowerLimitResponse) {}
    rpc FailsafeDurationMinimum (FailsafeDurationMinimumRequest) returns (FailsafeDurationMinimumResponse) {}
    rpc WriteFailsafeDurationMinimum (WriteFailsafeDurationMinimumRequest) returns (WriteFailsafeDurationMinimumResponse) {}
    rpc StartHeartbeat (StartHeartbeatRequest) returns (StartHeartbeatResponse) {}
    rpc StopHeartbeat (StopHeartbeatRequest) returns (StopHeartbeatResponse) {}
    rpc IsHeartbeatWithinDuration (IsHeartbeatWithinDurationRequest) returns (IsHeartbeatWithinDurationResponse) {}
    rpc ProductionNominalMax (ProductionNominalMaxRequest) returns (ProductionNominalMaxResponse) {}
}
